import type { Post, Block, Category } from "./blog";

/**
 * Spanish blog content. Mirrors blog.ts post-for-post (same slugs/dates/categories)
 * with translated titles, excerpts, and body. Rendered by the /es resources pages.
 */

export const categoriesEs: Record<Category, string> = {
  "Hernando County rental market": "Mercado de renta del Condado de Hernando",
  "Landlord tips": "Consejos para propietarios",
  "Florida rental basics": "Conceptos básicos de renta en Florida",
  Maintenance: "Mantenimiento",
  "Tenant screening": "Selección de inquilinos",
  "Property management fees": "Tarifas de administración",
  "Investor strategy": "Estrategia de inversión",
  "Hurricane preparedness": "Preparación para huracanes",
};

const cta: Block = {
  t: "note",
  text: "¿Quiere una estimación de renta informada por el mercado para su propiedad? Solicite un Análisis de Renta Gratis — sin compromiso.",
};

export const postsEs: Post[] = [
  {
    slug: "how-much-does-property-management-cost-in-hernando-county",
    title: "¿Cuánto Cuesta la Administración de Propiedades en el Condado de Hernando?",
    category: "Property management fees",
    excerpt:
      "Un desglose en lenguaje sencillo de las tarifas típicas de administración en el Condado de Hernando — administración mensual, arrendamiento, renovación y las tarifas a vigilar.",
    date: "2026-01-15",
    readingMinutes: 6,
    body: [
      { t: "p", text: "El precio de la administración de propiedades debería ser fácil de entender. En el Condado de Hernando, la mayoría de la administración residencial se compone de unas pocas tarifas principales. Así funcionan normalmente y qué debe revisar." },
      { t: "h2", text: "Las tarifas principales" },
      { t: "ul", items: [
        "Tarifa de administración mensual — una tarifa fija o porcentaje por la administración continua. Los planes de TrueNorth comienzan en $99/mes.",
        "Tarifa de arrendamiento / colocación — se cobra cuando se coloca un nuevo inquilino, a menudo un porcentaje de la primera renta.",
        "Tarifa de renovación — una tarifa menor para negociar y documentar una renovación de contrato.",
        "Tarifas de inspección — según la frecuencia y el plan.",
      ]},
      { t: "h2", text: "Tarifas que los propietarios deberían cuestionar" },
      { t: "p", text: "Las tarifas que frustran a los propietarios suelen ser las poco claras: recargos de mantenimiento, cargos «administrativos» vagos y términos de cancelación confusos. Un administrador transparente los detalla antes de que usted firme." },
      { t: "h2", text: "Qué define su precio específico" },
      { t: "ul", items: ["Tipo y tamaño de la propiedad", "Ubicación y condición", "Alcance de los servicios que elija", "Si combina el servicio completo o elige por servicio"] },
      { t: "note", text: "Los precios están sujetos al tipo de propiedad, ubicación, condición, alcance del servicio y un acuerdo de administración firmado." },
      cta,
    ],
  },
  {
    slug: "self-manage-or-hire-a-property-manager",
    title: "¿Debería Autoadministrar o Contratar a un Administrador?",
    category: "Landlord tips",
    excerpt: "Un marco práctico para decidir si administrar su propia renta o contratar a un profesional — según su tiempo, distancia y tolerancia al riesgo.",
    date: "2026-01-22",
    readingMinutes: 7,
    body: [
      { t: "p", text: "Autoadministrar puede funcionar bien — hasta que deja de funcionar. La respuesta correcta depende de su tiempo, su distancia de la propiedad y cómo maneja las partes que a la mayoría de los propietarios no les gustan." },
      { t: "h2", text: "Autoadministrar puede convenirle si…" },
      { t: "ul", items: ["Vive cerca de la propiedad", "Tiene tiempo para llamadas de inquilinos y coordinación", "Se siente cómodo con la selección, los contratos y los requisitos de Florida", "Tiene proveedores confiables disponibles"] },
      { t: "h2", text: "Un administrador suele tener sentido si…" },
      { t: "ul", items: ["Está fuera del área o del estado", "La vacancia o la rotación le están costando", "No confía en su proceso de selección", "La coordinación de mantenimiento le consume las tardes"] },
      { t: "h2", text: "El costo real de autoadministrar" },
      { t: "p", text: "Autoadministrar no es gratis — cuesta tiempo, y los errores (un mal inquilino, una rotación lenta, una reparación sin documentar) pueden costar mucho más que una tarifa de administración. Pese ambos." },
      cta,
    ],
  },
  {
    slug: "spring-hill-rental-property-owner-checklist",
    title: "Lista de Verificación para Propietarios de Renta en Spring Hill",
    category: "Hernando County rental market",
    excerpt: "Una lista de principio a fin para propietarios de Spring Hill — desde el precio y la preparación hasta la selección y la administración continua.",
    date: "2026-02-03",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Tener una renta en Spring Hill es una oportunidad, pero los detalles importan. Use esta lista para mantener su propiedad rentada y protegida." },
      { t: "h2", text: "Antes de publicar" },
      { t: "ul", items: ["Fije el precio según el vecindario, no un promedio de todo el condado", "Complete las reparaciones y la limpieza de preparación", "Confirme las reglas de HOA que afectan a los inquilinos", "Reúna el contrato, las divulgaciones y la documentación"] },
      { t: "h2", text: "Durante el arrendamiento" },
      { t: "ul", items: ["Fotos y publicación profesionales", "Selección consistente y conforme a la vivienda justa", "Términos de contrato claros", "Condición de entrada documentada"] },
      { t: "h2", text: "De forma continua" },
      { t: "ul", items: ["Cobro de renta en línea", "Mantenimiento documentado con umbrales de aprobación", "Inspecciones periódicas", "Reportes mensuales claros"] },
      cta,
    ],
  },
  {
    slug: "prepare-your-hernando-county-rental-for-a-new-tenant",
    title: "Cómo Preparar su Renta del Condado de Hernando para un Nuevo Inquilino",
    category: "Maintenance",
    excerpt: "Una rotación bien hecha reduce la vacancia y marca el tono con un nuevo inquilino. Esto es lo que debe cubrir.",
    date: "2026-02-12",
    readingMinutes: 5,
    body: [
      { t: "p", text: "La rotación entre inquilinos es su oportunidad de proteger la propiedad y rentar rápido. Un proceso de preparación minucioso y documentado da resultados." },
      { t: "h2", text: "Limpie e inspeccione" },
      { t: "ul", items: ["Limpieza profunda, incluyendo electrodomésticos y pisos", "Inspeccione el aire acondicionado, la plomería y la electricidad", "Cambie los filtros y pruebe los detectores de humo/CO", "Cambie o actualice las cerraduras"] },
      { t: "h2", text: "Repare y documente" },
      { t: "ul", items: ["Atienda el mantenimiento diferido antes de que crezca", "Fotografíe la condición de entrada a fondo", "Confirme que los elementos de seguridad cumplan los requisitos"] },
      { t: "h2", text: "Atractivo y rapidez" },
      { t: "p", text: "Pequeños toques en el exterior ayudan a que una propiedad se muestre bien, y una rotación rápida y organizada reduce los días de vacancia — uno de los mayores costos ocultos para los propietarios." },
      cta,
    ],
  },
  {
    slug: "out-of-state-landlords-managing-florida-property",
    title: "Lo que los Propietarios de Fuera del Estado Deben Saber sobre Administrar en Florida",
    category: "Florida rental basics",
    excerpt: "Administrar una renta de Florida desde lejos es muy posible — con los sistemas adecuados, ojos locales y reportes claros.",
    date: "2026-02-20",
    readingMinutes: 6,
    body: [
      { t: "p", text: "La propiedad desde fuera del estado funciona bien cuando hay responsabilidad local y visibilidad. Esto es lo que debe planear específicamente en Florida." },
      { t: "h2", text: "La presencia local importa" },
      { t: "p", text: "Alguien tiene que responder físicamente al mantenimiento, las inspecciones y los eventos climáticos. Un administrador local lo provee sin que usted tenga que volar." },
      { t: "h2", text: "Consideraciones específicas de Florida" },
      { t: "ul", items: ["Preparación ante huracanes y tormentas", "Humedad y mantenimiento del aire acondicionado", "Manejo del depósito de seguridad según la ley de Florida", "Consideraciones de seguro para propietarios ausentes"] },
      { t: "h2", text: "Visibilidad desde cualquier lugar" },
      { t: "p", text: "Un portal del propietario en línea y estados de cuenta mensuales claros le permiten mantenerse informado desde otro estado o zona horaria." },
      { t: "note", text: "Este artículo es información general, no asesoría legal, fiscal ni de seguros. Consulte a profesionales con licencia para su situación." },
      cta,
    ],
  },
  {
    slug: "property-management-fees-explained",
    title: "Tarifas de Administración Explicadas: Qué Deben Buscar los Propietarios",
    category: "Property management fees",
    excerpt: "No todas las estructuras de tarifas son iguales. Aprenda a comparar administradores por transparencia, no solo por el precio principal.",
    date: "2026-03-02",
    readingMinutes: 6,
    body: [
      { t: "p", text: "La tarifa principal más baja no siempre es el mejor trato. Lo que importa es la transparencia total — saber exactamente qué pagará y cuándo." },
      { t: "h2", text: "Preguntas que hacer sobre las tarifas" },
      { t: "ul", items: ["¿La tarifa de administración es fija o un porcentaje?", "¿Cuál es la tarifa de arrendamiento y cuándo se cobra?", "¿Se recargan los costos de mantenimiento?", "¿Hay tarifas de configuración, administrativas o de cancelación?", "¿Cómo se documentan las facturas de proveedores?"] },
      { t: "h2", text: "Transparencia sobre trucos" },
      { t: "p", text: "Una estructura de tarifas clara y publicada suele superar a una tarifa «baja» llena de cargos sorpresa. Lea el acuerdo, no solo el folleto." },
      cta,
    ],
  },
  {
    slug: "reduce-vacancy-in-a-hernando-county-rental",
    title: "Cómo Reducir la Vacancia en una Renta del Condado de Hernando",
    category: "Landlord tips",
    excerpt: "La vacancia es uno de los mayores costos ocultos de tener una renta. Estas son las palancas que de verdad la mueven.",
    date: "2026-03-10",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Cada semana vacía es ingreso perdido. La buena noticia: la mayoría de la vacancia es controlable con precio, presentación y rapidez." },
      { t: "h2", text: "Fije el precio según el mercado" },
      { t: "p", text: "Sobrevalorar es la causa número uno de las vacancias largas. El precio informado por el mercado basado en comparables locales se renta más rápido y a menudo genera más durante el año." },
      { t: "h2", text: "Muéstrela bien, rótela rápido" },
      { t: "ul", items: ["Fotos profesionales y una publicación completa", "Una rotación de preparación rápida y organizada", "Visitas y manejo de solicitudes receptivos", "Renovaciones proactivas para evitar la rotación por completo"] },
      cta,
    ],
  },
  {
    slug: "rental-property-hurricane-preparedness-checklist-florida",
    title: "Lista de Preparación para Huracanes para Propietarios de Florida",
    category: "Hurricane preparedness",
    excerpt: "Una lista práctica y lista para la temporada para proteger su renta de Florida y a sus inquilinos antes, durante y después de una tormenta.",
    date: "2026-03-18",
    readingMinutes: 6,
    body: [
      { t: "p", text: "Los propietarios de Florida no pueden controlar el clima, pero pueden estar listos. Un plan documentado protege su propiedad y a sus inquilinos." },
      { t: "h2", text: "Antes de la temporada" },
      { t: "ul", items: ["Revise la cobertura de seguro con su agente", "Inspeccione el techo, las canaletas y el drenaje", "Pode los árboles y asegure los objetos exteriores", "Confirme la información de contacto de emergencia del inquilino"] },
      { t: "h2", text: "Cuando amenaza una tormenta" },
      { t: "ul", items: ["Comuníquese con claridad con los inquilinos", "Documente la condición de la propiedad antes de la tormenta", "Priorice el triaje de emergencia para problemas de seguridad"] },
      { t: "h2", text: "Después de la tormenta" },
      { t: "ul", items: ["Inspeccione y documente los daños con fotos", "Coordine las reparaciones de emergencia", "Mantenga informados a los propietarios"] },
      { t: "note", text: "Las preguntas de seguro y legales deben dirigirse a profesionales con licencia. Esto es solo información general." },
      cta,
    ],
  },
  {
    slug: "what-makes-a-rental-property-rent-ready",
    title: "¿Qué Hace que una Propiedad Esté Lista para Rentar?",
    category: "Maintenance",
    excerpt: "«Listo para rentar» significa más que limpio. Este es el estándar que ayuda a que una propiedad se rente rápido y conserve su valor.",
    date: "2026-03-26",
    readingMinutes: 4,
    body: [
      { t: "p", text: "Listo para rentar es un estándar, no una sensación. Cumplirlo de forma consistente reduce la vacancia y marca las expectativas con los inquilinos." },
      { t: "h2", text: "El estándar de listo para rentar" },
      { t: "ul", items: ["Profesionalmente limpio en todas partes", "Todos los sistemas funcionales (aire, plomería, electricidad)", "Elementos de seguridad colocados y probados", "Sin mantenimiento diferido pendiente", "Condición de entrada documentada"] },
      { t: "p", text: "Una propiedad que cumple este estándar se muestra mejor, atrae solicitantes más fuertes y lo protege en cualquier discusión futura sobre el depósito." },
      cta,
    ],
  },
  {
    slug: "questions-to-ask-before-hiring-a-property-manager",
    title: "Preguntas que Hacer Antes de Contratar a un Administrador",
    category: "Landlord tips",
    excerpt: "¿Está entrevistando administradores? Estas preguntas van más allá del discurso de venta hacia lo que realmente importa para su propiedad.",
    date: "2026-04-04",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Un buen administrador de propiedades debería recibir bien las preguntas difíciles. Use estas para comparar administradores por su sustancia." },
      { t: "h2", text: "Precios y transparencia" },
      { t: "ul", items: ["¿Qué cubren exactamente sus tarifas?", "¿Se recargan los costos de mantenimiento?", "¿Cuáles son los términos de cancelación?"] },
      { t: "h2", text: "Operaciones" },
      { t: "ul", items: ["¿Cómo seleccionan a los inquilinos?", "¿Puedo definir umbrales de aprobación de mantenimiento?", "¿Cómo y cuándo tendré noticias suyas?", "¿Qué software usan y qué veré?"] },
      { t: "h2", text: "Local y cumplimiento" },
      { t: "ul", items: ["¿Qué tan bien conocen mi mercado?", "¿Cómo manejan los requisitos específicos de Florida?", "¿Operan bajo una correduría activa de Florida?"] },
      cta,
    ],
  },
];

export const getPostEs = (slug: string) => postsEs.find((p) => p.slug === slug);
