import type { Post, Block, Category } from "./blog";

/**
 * Spanish blog content. Mirrors blog.ts post-for-post (same slugs/dates/categories)
 * with translated titles, excerpts, and body. Rendered by the /es resources pages.
 */

export const categoriesEs: Record<Category, string> = {
  "Hernando County rental market": "Mercado de renta del Condado de Hernando",
  "Landlord tips": "Consejos para propietarios",
  "Florida rental basics": "Conceptos básicos de renta en Florida",
  Maintenance: "Mantenimiento",
  "Tenant screening": "Selección de inquilinos",
  "Property management fees": "Tarifas de administración",
  "Investor strategy": "Estrategia de inversión",
  "Hurricane preparedness": "Preparación para huracanes",
};

const cta: Block = {
  t: "note",
  text: "¿Quiere una estimación de renta informada por el mercado para su propiedad? Solicite un Análisis de Renta Gratis — sin compromiso.",
};

export const postsEs: Post[] = [
  {
    slug: "how-much-does-property-management-cost-in-hernando-county",
    title: "¿Cuánto Cuesta la Administración de Propiedades en el Condado de Hernando?",
    category: "Property management fees",
    excerpt:
      "Un desglose en lenguaje sencillo de las tarifas típicas de administración en el Condado de Hernando — administración mensual, arrendamiento, renovación y las tarifas a vigilar.",
    date: "2026-01-15",
    readingMinutes: 6,
    body: [
      { t: "p", text: "El precio de la administración de propiedades debería ser fácil de entender. En el Condado de Hernando, la mayoría de la administración residencial se compone de unas pocas tarifas principales. Así funcionan normalmente y qué debe revisar." },
      { t: "h2", text: "Las tarifas principales" },
      { t: "ul", items: [
        "Tarifa de administración mensual — una tarifa fija o porcentaje por la administración continua. Los planes de TrueNorth comienzan en $99/mes.",
        "Tarifa de arrendamiento / colocación — se cobra cuando se coloca un nuevo inquilino, a menudo un porcentaje de la primera renta.",
        "Tarifa de renovación — una tarifa menor para negociar y documentar una renovación de contrato.",
        "Tarifas de inspección — según la frecuencia y el plan.",
      ]},
      { t: "h2", text: "Tarifas que los propietarios deberían cuestionar" },
      { t: "p", text: "Las tarifas que frustran a los propietarios suelen ser las poco claras: recargos de mantenimiento, cargos «administrativos» vagos y términos de cancelación confusos. Un administrador transparente los detalla antes de que usted firme." },
      { t: "h2", text: "Qué define su precio específico" },
      { t: "ul", items: ["Tipo y tamaño de la propiedad", "Ubicación y condición", "Alcance de los servicios que elija", "Si combina el servicio completo o elige por servicio"] },
      { t: "note", text: "Los precios están sujetos al tipo de propiedad, ubicación, condición, alcance del servicio y un acuerdo de administración firmado." },
      cta,
    ],
  },
  {
    slug: "self-manage-or-hire-a-property-manager",
    title: "¿Debería Autoadministrar o Contratar a un Administrador?",
    category: "Landlord tips",
    excerpt: "Un marco práctico para decidir si administrar su propia renta o contratar a un profesional — según su tiempo, distancia y tolerancia al riesgo.",
    date: "2026-01-22",
    readingMinutes: 7,
    body: [
      { t: "p", text: "Autoadministrar puede funcionar bien — hasta que deja de funcionar. La respuesta correcta depende de su tiempo, su distancia de la propiedad y cómo maneja las partes que a la mayoría de los propietarios no les gustan." },
      { t: "h2", text: "Autoadministrar puede convenirle si…" },
      { t: "ul", items: ["Vive cerca de la propiedad", "Tiene tiempo para llamadas de inquilinos y coordinación", "Se siente cómodo con la selección, los contratos y los requisitos de Florida", "Tiene proveedores confiables disponibles"] },
      { t: "h2", text: "Un administrador suele tener sentido si…" },
      { t: "ul", items: ["Está fuera del área o del estado", "La vacancia o la rotación le están costando", "No confía en su proceso de selección", "La coordinación de mantenimiento le consume las tardes"] },
      { t: "h2", text: "El costo real de autoadministrar" },
      { t: "p", text: "Autoadministrar no es gratis — cuesta tiempo, y los errores (un mal inquilino, una rotación lenta, una reparación sin documentar) pueden costar mucho más que una tarifa de administración. Pese ambos." },
      cta,
    ],
  },
  {
    slug: "spring-hill-rental-property-owner-checklist",
    title: "Lista de Verificación para Propietarios de Renta en Spring Hill",
    category: "Hernando County rental market",
    excerpt: "Una lista de principio a fin para propietarios de Spring Hill — desde el precio y la preparación hasta la selección y la administración continua.",
    date: "2026-02-03",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Tener una renta en Spring Hill es una oportunidad, pero los detalles importan. Use esta lista para mantener su propiedad rentada y protegida." },
      { t: "h2", text: "Antes de publicar" },
      { t: "ul", items: ["Fije el precio según el vecindario, no un promedio de todo el condado", "Complete las reparaciones y la limpieza de preparación", "Confirme las reglas de HOA que afectan a los inquilinos", "Reúna el contrato, las divulgaciones y la documentación"] },
      { t: "h2", text: "Durante el arrendamiento" },
      { t: "ul", items: ["Fotos y publicación profesionales", "Selección consistente y conforme a la vivienda justa", "Términos de contrato claros", "Condición de entrada documentada"] },
      { t: "h2", text: "De forma continua" },
      { t: "ul", items: ["Cobro de renta en línea", "Mantenimiento documentado con umbrales de aprobación", "Inspecciones periódicas", "Reportes mensuales claros"] },
      cta,
    ],
  },
  {
    slug: "prepare-your-hernando-county-rental-for-a-new-tenant",
    title: "Cómo Preparar su Renta del Condado de Hernando para un Nuevo Inquilino",
    category: "Maintenance",
    excerpt: "Una rotación bien hecha reduce la vacancia y marca el tono con un nuevo inquilino. Esto es lo que debe cubrir.",
    date: "2026-02-12",
    readingMinutes: 5,
    body: [
      { t: "p", text: "La rotación entre inquilinos es su oportunidad de proteger la propiedad y rentar rápido. Un proceso de preparación minucioso y documentado da resultados." },
      { t: "h2", text: "Limpie e inspeccione" },
      { t: "ul", items: ["Limpieza profunda, incluyendo electrodomésticos y pisos", "Inspeccione el aire acondicionado, la plomería y la electricidad", "Cambie los filtros y pruebe los detectores de humo/CO", "Cambie o actualice las cerraduras"] },
      { t: "h2", text: "Repare y documente" },
      { t: "ul", items: ["Atienda el mantenimiento diferido antes de que crezca", "Fotografíe la condición de entrada a fondo", "Confirme que los elementos de seguridad cumplan los requisitos"] },
      { t: "h2", text: "Atractivo y rapidez" },
      { t: "p", text: "Pequeños toques en el exterior ayudan a que una propiedad se muestre bien, y una rotación rápida y organizada reduce los días de vacancia — uno de los mayores costos ocultos para los propietarios." },
      cta,
    ],
  },
  {
    slug: "out-of-state-landlords-managing-florida-property",
    title: "Lo que los Propietarios de Fuera del Estado Deben Saber sobre Administrar en Florida",
    category: "Florida rental basics",
    excerpt: "Administrar una renta de Florida desde lejos es muy posible — con los sistemas adecuados, ojos locales y reportes claros.",
    date: "2026-02-20",
    readingMinutes: 6,
    body: [
      { t: "p", text: "La propiedad desde fuera del estado funciona bien cuando hay responsabilidad local y visibilidad. Esto es lo que debe planear específicamente en Florida." },
      { t: "h2", text: "La presencia local importa" },
      { t: "p", text: "Alguien tiene que responder físicamente al mantenimiento, las inspecciones y los eventos climáticos. Un administrador local lo provee sin que usted tenga que volar." },
      { t: "h2", text: "Consideraciones específicas de Florida" },
      { t: "ul", items: ["Preparación ante huracanes y tormentas", "Humedad y mantenimiento del aire acondicionado", "Manejo del depósito de seguridad según la ley de Florida", "Consideraciones de seguro para propietarios ausentes"] },
      { t: "h2", text: "Visibilidad desde cualquier lugar" },
      { t: "p", text: "Un portal del propietario en línea y estados de cuenta mensuales claros le permiten mantenerse informado desde otro estado o zona horaria." },
      { t: "note", text: "Este artículo es información general, no asesoría legal, fiscal ni de seguros. Consulte a profesionales con licencia para su situación." },
      cta,
    ],
  },
  {
    slug: "property-management-fees-explained",
    title: "Tarifas de Administración Explicadas: Qué Deben Buscar los Propietarios",
    category: "Property management fees",
    excerpt: "No todas las estructuras de tarifas son iguales. Aprenda a comparar administradores por transparencia, no solo por el precio principal.",
    date: "2026-03-02",
    readingMinutes: 6,
    body: [
      { t: "p", text: "La tarifa principal más baja no siempre es el mejor trato. Lo que importa es la transparencia total — saber exactamente qué pagará y cuándo." },
      { t: "h2", text: "Preguntas que hacer sobre las tarifas" },
      { t: "ul", items: ["¿La tarifa de administración es fija o un porcentaje?", "¿Cuál es la tarifa de arrendamiento y cuándo se cobra?", "¿Se recargan los costos de mantenimiento?", "¿Hay tarifas de configuración, administrativas o de cancelación?", "¿Cómo se documentan las facturas de proveedores?"] },
      { t: "h2", text: "Transparencia sobre trucos" },
      { t: "p", text: "Una estructura de tarifas clara y publicada suele superar a una tarifa «baja» llena de cargos sorpresa. Lea el acuerdo, no solo el folleto." },
      cta,
    ],
  },
  {
    slug: "reduce-vacancy-in-a-hernando-county-rental",
    title: "Cómo Reducir la Vacancia en una Renta del Condado de Hernando",
    category: "Landlord tips",
    excerpt: "La vacancia es uno de los mayores costos ocultos de tener una renta. Estas son las palancas que de verdad la mueven.",
    date: "2026-03-10",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Cada semana vacía es ingreso perdido. La buena noticia: la mayoría de la vacancia es controlable con precio, presentación y rapidez." },
      { t: "h2", text: "Fije el precio según el mercado" },
      { t: "p", text: "Sobrevalorar es la causa número uno de las vacancias largas. El precio informado por el mercado basado en comparables locales se renta más rápido y a menudo genera más durante el año." },
      { t: "h2", text: "Muéstrela bien, rótela rápido" },
      { t: "ul", items: ["Fotos profesionales y una publicación completa", "Una rotación de preparación rápida y organizada", "Visitas y manejo de solicitudes receptivos", "Renovaciones proactivas para evitar la rotación por completo"] },
      cta,
    ],
  },
  {
    slug: "rental-property-hurricane-preparedness-checklist-florida",
    title: "Lista de Preparación para Huracanes para Propietarios de Florida",
    category: "Hurricane preparedness",
    excerpt: "Una lista práctica y lista para la temporada para proteger su renta de Florida y a sus inquilinos antes, durante y después de una tormenta.",
    date: "2026-03-18",
    readingMinutes: 6,
    body: [
      { t: "p", text: "Los propietarios de Florida no pueden controlar el clima, pero pueden estar listos. Un plan documentado protege su propiedad y a sus inquilinos." },
      { t: "h2", text: "Antes de la temporada" },
      { t: "ul", items: ["Revise la cobertura de seguro con su agente", "Inspeccione el techo, las canaletas y el drenaje", "Pode los árboles y asegure los objetos exteriores", "Confirme la información de contacto de emergencia del inquilino"] },
      { t: "h2", text: "Cuando amenaza una tormenta" },
      { t: "ul", items: ["Comuníquese con claridad con los inquilinos", "Documente la condición de la propiedad antes de la tormenta", "Priorice el triaje de emergencia para problemas de seguridad"] },
      { t: "h2", text: "Después de la tormenta" },
      { t: "ul", items: ["Inspeccione y documente los daños con fotos", "Coordine las reparaciones de emergencia", "Mantenga informados a los propietarios"] },
      { t: "note", text: "Las preguntas de seguro y legales deben dirigirse a profesionales con licencia. Esto es solo información general." },
      cta,
    ],
  },
  {
    slug: "what-makes-a-rental-property-rent-ready",
    title: "¿Qué Hace que una Propiedad Esté Lista para Rentar?",
    category: "Maintenance",
    excerpt: "«Listo para rentar» significa más que limpio. Este es el estándar que ayuda a que una propiedad se rente rápido y conserve su valor.",
    date: "2026-03-26",
    readingMinutes: 4,
    body: [
      { t: "p", text: "Listo para rentar es un estándar, no una sensación. Cumplirlo de forma consistente reduce la vacancia y marca las expectativas con los inquilinos." },
      { t: "h2", text: "El estándar de listo para rentar" },
      { t: "ul", items: ["Profesionalmente limpio en todas partes", "Todos los sistemas funcionales (aire, plomería, electricidad)", "Elementos de seguridad colocados y probados", "Sin mantenimiento diferido pendiente", "Condición de entrada documentada"] },
      { t: "p", text: "Una propiedad que cumple este estándar se muestra mejor, atrae solicitantes más fuertes y lo protege en cualquier discusión futura sobre el depósito." },
      cta,
    ],
  },
  {
    slug: "questions-to-ask-before-hiring-a-property-manager",
    title: "Preguntas que Hacer Antes de Contratar a un Administrador",
    category: "Landlord tips",
    excerpt: "¿Está entrevistando administradores? Estas preguntas van más allá del discurso de venta hacia lo que realmente importa para su propiedad.",
    date: "2026-04-04",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Un buen administrador de propiedades debería recibir bien las preguntas difíciles. Use estas para comparar administradores por su sustancia." },
      { t: "h2", text: "Precios y transparencia" },
      { t: "ul", items: ["¿Qué cubren exactamente sus tarifas?", "¿Se recargan los costos de mantenimiento?", "¿Cuáles son los términos de cancelación?"] },
      { t: "h2", text: "Operaciones" },
      { t: "ul", items: ["¿Cómo seleccionan a los inquilinos?", "¿Puedo definir umbrales de aprobación de mantenimiento?", "¿Cómo y cuándo tendré noticias suyas?", "¿Qué software usan y qué veré?"] },
      { t: "h2", text: "Local y cumplimiento" },
      { t: "ul", items: ["¿Qué tan bien conocen mi mercado?", "¿Cómo manejan los requisitos específicos de Florida?", "¿Operan bajo una correduría activa de Florida?"] },
      cta,
    ],
  },
  {
    slug: "how-to-price-your-spring-hill-rental",
    title: "Cómo Fijar la Renta de su Propiedad en Spring Hill Sin Adivinar",
    category: "Hernando County rental market",
    excerpt: "Si el precio es muy alto, la casa se queda vacía. Si es muy bajo, pierde ingresos durante todo el contrato. Así se llega al número correcto.",
    date: "2026-09-11",
    readingMinutes: 5,
    body: [
      { t: "p", text: "Fijar la renta es un método, no una corazonada. Los propietarios que usan comparables reales rentan más rápido y suelen ganar más en el año que quienes empiezan alto y esperan." },
      { t: "h2", text: "Use rentas cerradas, no precios pedidos" },
      { t: "p", text: "Los precios pedidos muestran lo que otros propietarios esperan cobrar. Las rentas cerradas muestran lo que los inquilinos realmente pagaron. Compare casas con el mismo número de habitaciones y baños, tamaño, antigüedad y condición similares, en la misma zona de Spring Hill." },
      { t: "h2", text: "Ajuste por lo que los inquilinos pagan de más" },
      { t: "ul", items: [
        "Garaje y patio cercado",
        "Política que acepta mascotas (con renta o cargo por mascota donde se permita)",
        "Cocina y pisos actualizados, lavadora y secadora",
        "Servicio de jardín o piscina incluido",
        "Acceso fácil al Suncoast Parkway y la US-19 para quienes viajan al trabajo",
      ]},
      { t: "h2", text: "Deje que los primeros 10 días le respondan" },
      { t: "p", text: "Con buenas fotos y un anuncio completo, una casa con buen precio recibe consultas y visitas constantes en la primera o segunda semana. Si no ocurre, el precio suele ser la razón. Un ajuste pequeño y temprano cuesta mucho menos que un mes vacío." },
      { t: "note", text: "Las cuentas: en una renta de $2,200/mes, bajar $50 cuesta $600 en un contrato de 12 meses. Un mes adicional vacío cuesta $2,200." },
      cta,
    ],
  },
  {
    slug: "tenant-screening-process-florida-landlords",
    title: "Cómo Seleccionar Inquilinos de Forma Justa y Consistente en Florida",
    category: "Tenant screening",
    excerpt: "Una buena selección protege la propiedad, al propietario y a cada solicitante. La clave: criterios por escrito, aplicados igual cada vez.",
    date: "2026-09-11",
    readingMinutes: 6,
    body: [
      { t: "p", text: "La mayoría de los problemas con inquilinos empiezan en la solicitud. Un buen proceso de selección no se trata de ser estricto, sino de ser consistente: los mismos criterios escritos, aplicados a cada solicitante, en el orden en que llegan las solicitudes." },
      { t: "h2", text: "Empiece con criterios por escrito" },
      { t: "ul", items: [
        "Ingresos en relación con la renta (muchos administradores usan un múltiplo como 2.5–3 veces la renta mensual)",
        "Historial de crédito y de pagos, revisando patrones y no solo un puntaje",
        "Historial de renta verificable y referencias de arrendadores",
        "Desalojos previos",
        "Límites de ocupación conforme a los códigos aplicables",
      ]},
      { t: "p", text: "Ponga sus criterios por escrito antes de publicar el anuncio y compártalos con cada solicitante que los pida." },
      { t: "h2", text: "Verifique, no suponga" },
      { t: "ul", items: [
        "Confirme ingresos con talones de pago, carta de oferta de empleo o estados de cuenta",
        "Llame a arrendadores anteriores y pregunte si volverían a rentarle al solicitante",
        "Compare la identificación con fotografía con la solicitud",
        "Documente la razón de cada aprobación o rechazo",
      ]},
      { t: "h2", text: "La vivienda justa es parte de la selección" },
      { t: "p", text: "La Ley federal de Vivienda Justa y la Ley de Vivienda Justa de Florida prohíben la discriminación por raza, color, origen nacional, religión, sexo, estado familiar y discapacidad, y algunas ordenanzas locales agregan protecciones. Dé a cada consulta las mismas respuestas, los mismos criterios y los mismos plazos." },
      { t: "ul", items: [
        "Las solicitudes de animales de asistencia son solicitudes de acomodo razonable, no preguntas sobre la política de mascotas",
        "Prohibir cualquier antecedente penal de forma general puede crear riesgo bajo la ley de vivienda justa; la guía de HUD favorece criterios relevantes e individualizados",
        "Anuncie la propiedad, nunca al inquilino «ideal»",
      ]},
      { t: "h2", text: "Cómo lo maneja TrueNorth" },
      { t: "p", text: "TrueNorth recibe solicitudes en línea a través de RentRedi y aplica los mismos criterios publicados a cada solicitante, documentando cada decisión." },
      { t: "note", text: "Este artículo es información general, no asesoramiento legal. Las reglas de vivienda justa y selección cambian. Consulte a un abogado de Florida sobre su situación." },
      cta,
    ],
  },
  {
    slug: "florida-security-deposit-rules-for-landlords",
    title: "Reglas de Depósitos de Seguridad en Florida que Todo Propietario Debe Conocer",
    category: "Florida rental basics",
    excerpt: "Florida fija plazos estrictos para guardar y devolver depósitos. Si incumple uno, puede perder el derecho a reclamar. Este es el calendario.",
    date: "2026-09-11",
    readingMinutes: 6,
    body: [
      { t: "p", text: "Los depósitos de seguridad en Florida se rigen por la Sección 83.49 de los Estatutos de Florida. Las reglas son específicas, los plazos son cortos y un paso omitido puede costarle al propietario el derecho a descontar cualquier cantidad." },
      { t: "h2", text: "Cómo guardar el depósito" },
      { t: "ul", items: [
        "Manténgalo en una cuenta bancaria separada en Florida (con o sin intereses), o use una fianza según lo permite el estatuto",
        "No lo mezcle con fondos operativos ni lo use antes de que termine el arrendamiento",
        "Dentro de los 30 días de recibirlo, notifique por escrito al inquilino cómo y dónde se guarda, con el lenguaje de divulgación que exige el estatuto",
      ]},
      { t: "h2", text: "Cuando el inquilino se muda" },
      { t: "ul", items: [
        "Sin reclamo: devuelva el depósito completo dentro de 15 días",
        "Con reclamo: dentro de 30 días, envíe aviso escrito por correo certificado a la última dirección postal conocida del inquilino, indicando su intención de hacer un reclamo y el motivo",
        "El inquilino tiene 15 días después de recibir el aviso para objetar por escrito",
        "Si no hay objeción, descuente el reclamo y devuelva el saldo dentro de los 30 días de la fecha de su aviso",
      ]},
      { t: "p", text: "Si el aviso de 30 días no se envía a tiempo, el propietario generalmente pierde el derecho a hacer un reclamo sobre el depósito. Es el error más costoso de todo el proceso." },
      { t: "h2", text: "La documentación gana las disputas de depósito" },
      { t: "ul", items: [
        "Una inspección de entrada con fotos fechadas de cada habitación",
        "Una inspección de salida que repita las mismas habitaciones y ángulos",
        "Facturas detalladas de cada reparación que descuente",
        "Una línea clara entre el desgaste normal y el daño real",
      ]},
      { t: "h2", text: "Alternativas al depósito" },
      { t: "p", text: "Desde 2023, la ley de Florida (Sección 83.491) permite que los propietarios ofrezcan una tarifa mensual en lugar de un depósito de seguridad tradicional. Se requieren divulgaciones escritas específicas, y no es la mejor opción para todas las propiedades." },
      { t: "note", text: "Este artículo es información general, no asesoramiento legal. Los estatutos cambian. Confirme los requisitos vigentes con un abogado de Florida antes de basarse en ellos." },
      cta,
    ],
  },
  {
    slug: "numbers-to-run-before-buying-a-rental-in-hernando-county",
    title: "¿Va a Comprar una Propiedad de Renta en Hernando? Haga Estas Cuentas Primero",
    category: "Investor strategy",
    excerpt: "Una casa que se renta por más que la hipoteca aún puede perder dinero. Arme un presupuesto mensual completo antes de hacer una oferta.",
    date: "2026-09-11",
    readingMinutes: 7,
    body: [
      { t: "p", text: "Los anuncios venden lo positivo. Su trabajo antes de ofertar es encontrar lo negativo: cada costo mensual que la propiedad tendrá una vez que sea suya y esté rentada." },
      { t: "h2", text: "Empiece con una renta realista" },
      { t: "p", text: "Use casas comparables rentadas recientemente en la zona, no precios pedidos ni un promedio del condado. Un Análisis de Renta Gratis le da un punto de partida informado por el mercado." },
      { t: "h2", text: "Luego cuente cada costo mensual" },
      { t: "ul", items: [
        "Capital e intereses de la hipoteca",
        "Impuestos a la propiedad. Una propiedad de renta no tiene el límite de homestead, y el valor tasado normalmente se reajusta tras una venta, así que la factura del vendedor puede subestimar la suya",
        "Seguro. Las primas en Florida, incluida la cobertura contra viento, varían mucho según la edad del techo y la ubicación. Pida una cotización antes de ofertar, y cobertura contra inundaciones si aplica",
        "Cuotas de HOA o comunidad, y cualquier regla que restrinja rentar",
        "Administración de la propiedad",
        "Reserva por vacancia (5–8% de la renta es una cifra común de planificación)",
        "Reservas de mantenimiento y capital para techo, aire acondicionado y calentador de agua (5–10% de la renta)",
      ]},
      { t: "h2", text: "Un ejemplo con números" },
      { t: "ul", items: [
        "Renta: $2,100/mes",
        "Hipoteca (capital e intereses): $1,150",
        "Impuestos a la propiedad: $300",
        "Seguro: $210",
        "Administración: $150",
        "Reserva por vacancia (6%): $126",
        "Reservas de mantenimiento y capital (8%): $168",
        "Costo mensual total: $2,104, así que el flujo de caja es de aproximadamente −$4/mes",
      ]},
      { t: "p", text: "Aquí la renta supera la hipoteca por $950 y, aun así, la propiedad apenas llega al punto de equilibrio al contar todo. Eso no la convierte en un mal negocio, porque la plusvalía y el pago de capital también cuentan. Pero debe ser una decisión consciente, no una sorpresa." },
      { t: "note", text: "Las cifras anteriores son solo ilustrativas, no un pronóstico para ninguna propiedad. Pruebe la Calculadora de ROI con sus propios números." },
      { t: "h2", text: "Más allá de las cuentas mensuales" },
      { t: "ul", items: [
        "Edad del techo y del aire acondicionado, que afectan reparaciones y asegurabilidad en Florida",
        "Designación de zona de inundación",
        "Restricciones de HOA para rentar y plazos mínimos de contrato",
        "Demanda de inquilinos para ese tamaño y ubicación",
      ]},
      { t: "note", text: "Este artículo es información general, no asesoramiento de inversión, fiscal ni financiero. Consulte a profesionales con licencia antes de comprar." },
      cta,
    ],
  },
];

export const getPostEs = (slug: string) => postsEs.find((p) => p.slug === slug);
